### ISSUE TITLE
Powerline arrows aren't as large as the text bounding box

### ISSUE THREAD

**Issue by noahadvs** [JetBrains/JetBrainsMono#395]
Powerline arrows aren't as large as the text bounding box. This causes odd seams and extra space above the top and below the bottom of Powerline arrow characters.

JetBrains Mono 10pts:

![Screenshot_20210117_154547](https://user-images.githubusercontent.com/3580471/104855512-409c4f80-58db-11eb-9ecd-5214aa8cb89f.png)

Hack 10pts (no seams or extra space above and below arrows):

![Screenshot_20210117_155314](https://user-images.githubusercontent.com/3580471/104855684-257e0f80-58dc-11eb-991c-7c6af694660d.png)

Raw string: 

```
  ✗ 
```

[Starship prompt](https://starship.rs) configuration:

```toml
[character]
format = "[ ](fg:white bg:black)$symbol "
success_symbol = "[](fg:black)"
error_symbol = "[](fg:black bg:red)[ ✗ ](bg:red)[](fg:red)"
```

## System info

Operating System: openSUSE Tumbleweed 20210114

Application: Konsole (version 21.03.70, git master)

Qt Version: 5.15.2

FreeType version: 2.10.4

FreeType settings: antialiasing, slight hinting, RGB sub-pixel rendering

Screen resolution: 1920x1080

Scale factor: 1x
