### ISSUE TITLE
[Request] Easy way to add the font with css

### ISSUE THREAD

**Issue by MinerChAI** [JetBrains/JetBrainsMono#96]
Like with Fira Code you can
```css
@import url(https://cdn.jsdelivr.net/gh/tonsky/FiraCode@1.207/distr/fira_code.css);
```

**Comment by jmswrnr** [comment]
An easy to import css file like that would be nice! 

However, it is possible to link to the fonts via jsdelivr in your own css:

```css
@font-face{
  font-family: 'JetBrainsMono';
  src: url('https://cdn.jsdelivr.net/gh/JetBrains/JetBrainsMono/web/woff2/JetBrainsMono-Regular.woff2') format('woff2'),
    url('https://cdn.jsdelivr.net/gh/JetBrains/JetBrainsMono/web/woff/JetBrainsMono-Regular.woff') format('woff'),
    url('https://cdn.jsdelivr.net/gh/JetBrains/JetBrainsMono/ttf/JetBrainsMono-Regular.ttf') format('truetype');
  font-weight: 400;
  font-style: normal;
}
```
